version: '3'
services:
  my-service:
    image: v6
    networks:
      - my-network
networks:
  my-network:
    ipam:
      driver: bridge
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.254
